Add Vostok.Hosting
vostok-archives/core pull request #37
Opened 2017-11-02 08:54 UTC by spaceorc

2017-11-07 09:33 UTC, trurl123 commented on Vostok.Hosting/VostokHostBuilder.cs
> +                return new VostokHost(hostingEnvironment, async _ => throw new AggregateException("Failed to build host", e));
решарпер ругается, что будет запускаться синхронно, не найдены await-операторы

2017-11-07 09:53 UTC, trurl123 requested changes

2017-11-07 09:53 UTC, trurl123 commented on Vostok.Hosting.Core/VostokHostingEnvironment.cs
> +        private static readonly AsyncLocal<IVostokHostingEnvironment> hostingEnvironmentContainer = new AsyncLocal<IVostokHostingEnvironment>();
не понятен смысл использования в данном месте AsyncLocal

2017-11-07 19:13 UTC, spaceorc commented on Vostok.Hosting.Core/VostokHostingEnvironment.cs
> +        private static readonly AsyncLocal<IVostokHostingEnvironment> hostingEnvironmentContainer = new AsyncLocal<IVostokHostingEnvironment>();
Как раз так и задумано. Ты разве не видел варианты использования?

2017-11-07 19:14 UTC, spaceorc commented on Vostok.Hosting/VostokHostBuilder.cs
> +                return new VostokHost(hostingEnvironment, async _ => throw new AggregateException("Failed to build host", e));
не обращай внимания и все

2017-11-08 04:21 UTC, trurl123 requested changes

2017-11-08 04:22 UTC, trurl123 commented on Vostok.Hosting/VostokHostBuilder.cs
> +                return new VostokHost(hostingEnvironment, async _ => throw new AggregateException("Failed to build host", e));
почему нельзя удалить слово async?

2017-11-08 09:21 UTC, trurl123 requested changes

2017-11-08 09:21 UTC, trurl123 commented on Vostok.Hosting/VostokHostBuilder.cs
> +                            throw new InvalidOperationException($"Invalid value '{value}' for vostok.airlock.{propertyInfo.Name}");
Может использовать airlockSection.Path вместо строки vostok.airlock?

2017-11-27 10:19 UTC, merged