retriable call strategy
vostok-archives/core pull request #38
Opened 2017-11-03 07:26 UTC by trurl123

класс для реализации повторов операций

2017-11-03 10:50 UTC, spaceorc requested changes

2017-11-03 10:50 UTC, spaceorc commented on Vostok.Core/RetriableCall/ExceptionFinder.cs
> +                ? aggregateEx.InnerExceptions.LastOrDefault()
Не понял, почему тут не перебор всех InnerExceptions?

2017-11-03 10:50 UTC, spaceorc commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +    public interface IRetriableCallStrategy
Давай отдельные классы в отдельные файлы помещать

2017-11-03 10:50 UTC, spaceorc commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +            var cmp = string.CompareOrdinal(e1.Message, e2.Message);
Странно видеть на соседних строках CompareOrdinal и Compare(.. Ordinal) :)

2017-11-03 10:50 UTC, spaceorc commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +        public RetriableCallStrategy(int retriesBeforeStop = 5, int minDelayMs = 500, int maxDelayMs = 10000)
Предлагаю использовать TimeSpan-ы в такого рода местах

2017-11-03 10:50 UTC, spaceorc commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +        public T Call<T>(Func<T> action, Func<Exception, bool> isExceptionRetriable, ILog log)
Этого метода нет в интерфейсе

2017-11-03 10:50 UTC, spaceorc commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +            await CallAsync(async () =>
ConfigureAwait в библиотечном методе - это обязательно!

2017-11-03 10:50 UTC, spaceorc commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +                res = await action();
Тут наверняка решарпер говорит access to midified closure...
Я предпочитаю делать наоборот - этот метод реализовывать по честному, а в том методе перевызывать этот с Task<object>, с экшеном типа async () => { await action(); return null; }

2017-11-03 10:50 UTC, spaceorc commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +        public void Call(Action action, Func<Exception, bool> isExceptionRetriable, ILog log)
Этого метода тоже нет в интерфейсе

2017-11-03 10:50 UTC, spaceorc commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +                    await action();
ConfigureAwait обязательно

2017-11-03 10:50 UTC, spaceorc commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +            for (var failedTries = 0; failedTries < retriesBeforeStop; failedTries++)
Надо подумать, как тут бороться с дублированием кода

2017-11-03 10:50 UTC, spaceorc commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +                        log.Warn($"Try #{failedTries + 1} failed, retry after {delay.Milliseconds}ms: {ex}");
У нас же есть отдельный параметр exception для такого

2017-11-03 10:50 UTC, spaceorc commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +                    message = ex.Message;
Может, как раз этот retriableException.Message брать сюда?

2017-11-03 10:50 UTC, spaceorc commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +            throw new AggregateException(message, exceptions);
Кажется, что это идет вразрез с идеей await-а... Если поэвэйтить этот метод - AggregationException развернется...

2017-11-03 10:50 UTC, spaceorc commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +                        await Task.Delay(delay);
ConfigureAwait тоже

2017-11-03 10:50 UTC, spaceorc commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +                    {
Как-то много этих сравнений. Может, тоже как-то переделать этот код? В голову приходит что-то, типа выделить метод `TryOnce(... bool lastChance ...)`

2017-11-03 11:08 UTC, trurl123 commented on Vostok.Core/RetriableCall/ExceptionFinder.cs
> +                ? aggregateEx.InnerExceptions.LastOrDefault()
Чтобы проверка исключения происходила на всех вложенных. Бывает код, который вызывается, меняется и начинает оборачивать исключения в другие.

2017-11-03 11:19 UTC, trurl123 commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +            var cmp = string.CompareOrdinal(e1.Message, e2.Message);
на самом деле, не обратил внимания. Вообще классы написаны коллективным разумом в коннекторах. Я только асинхронность и нарастающие паузы прикрутил.

2017-11-03 11:21 UTC, trurl123 commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +        public RetriableCallStrategy(int retriesBeforeStop = 5, int minDelayMs = 500, int maxDelayMs = 10000)
если TimeSpan, то у них дефолтное значение можно задать только null, в этом только вижу неудобство

2017-11-03 11:27 UTC, trurl123 commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +                res = await action();
У меня не ругается. Ну давай так сделаем с фиктивным результатом.

2017-11-03 11:47 UTC, trurl123 commented on Vostok.Core/RetriableCall/ExceptionFinder.cs
> +                ? aggregateEx.InnerExceptions.LastOrDefault()
Абсолютно все нет смысла перебирать, решили как-то. В принципе для наших планируемых масштабов внедрения стоит перебирать все.

2017-11-07 04:27 UTC, trurl123 commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +        public void Call(Action action, Func<Exception, bool> isExceptionRetriable, ILog log)
убрал интерфейс

2017-11-07 04:30 UTC, trurl123 commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +                        log.Warn($"Try #{failedTries + 1} failed, retry after {delay.Milliseconds}ms: {ex}");
поправил

2017-11-07 04:30 UTC, trurl123 commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +            throw new AggregateException(message, exceptions);
написал тест на этот случай, ничего не разворачивается

2017-11-07 04:31 UTC, trurl123 commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +        public T Call<T>(Func<T> action, Func<Exception, bool> isExceptionRetriable, ILog log)
убрал интерфейс

2017-11-07 04:31 UTC, trurl123 commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +    public interface IRetriableCallStrategy
поправил

2017-11-07 19:12 UTC, spaceorc commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +        public RetriableCallStrategy(int retriesBeforeStop = 5, int minDelayMs = 500, int maxDelayMs = 10000)
На мой вкус, так это не надо делать дефолтов для такого класса. Абстрактная RetiableCallStrategy, серьезно?

2017-11-08 04:51 UTC, trurl123 commented on Vostok.Core/RetriableCall/RetriableCallStrategy.cs
> +        public RetriableCallStrategy(int retriesBeforeStop = 5, int minDelayMs = 500, int maxDelayMs = 10000)
Наоброт, не абсстрактная, а дефолтная.

2017-11-08 07:07 UTC, spaceorc approved these changes

2017-11-08 08:38 UTC, merged